### ISSUE TITLE
Servizio non più visibile su openlayers

### ISSUE THREAD

**Issue by enricofer** [enricofer/catasto#2]
Roberto Bosco <r.bosco74@gmail.com> | Roberto Bosco <r.bosco74@gmail.com> | lun 20 lug, 11:04 (5 giorni fa)

abbiamo recuperato il Vostro visualizzatore con OL x consultare i servizi wms del catasto.

La registrazione del video mostra i wms sovrapposti a OSM ma il navigatore non rappresenta i wms.

Volevamo chiederLe se è necessario impostare qualche parametro nel browser.

Vorremmo fare un test per capire le prestazioni.

Con Leaflet i servizi del catsto funzionano :
http://geomappando.com/maps/LEAF_catasto_WMS_2.html 

Se può darci una sintetica indicazione sarebbe gradita... stiamo facendo dei test per il Comune Sezze (LT).

Grazie in ogni caso.

Ufficio Tecnico 
Comune di Sezze (LT)

**Comment by enricofer** [comment]
Openlayers, di default, chiede al server il servizio WMS  nella versione 1.3.
Per qualche motivo sconosciuto il servizio WMS del catasto non viene più fornito nella versione 1.3 ma solo nella versione 1.1.1.
Quindi specificando la versione opportuna nella definizione del servizio tutto torna a funzionare: https://github.com/enricofer/catasto/commit/1b67c213a005b584851d1bafc361cf1e1b2bb803

Grazie per la segnalazione

**Comment by Cm-8** [comment]
Salve,
Da recenti consultazioni, mi risulta che il servizio sia tornato disponibile alla versione 1.3.0
